name: flutter_matrix_client
description: "A native Matrix client for Google TV optimized for D-pad remote navigation."
publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_riverpod: ^2.5.0
  open_filex: ^4.7.0
  package_info_plus: ^8.1.2
  matrix: ^12.0.0
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/
